export type SqlDifficulty = 'Easy' | 'Medium' | 'Hard' | 'Interview'

export interface SqlQuestion {
  id: string
  title: string
  difficulty: SqlDifficulty
  topic: string
  prompt: string
  solutionQuery: string
  /** True when row order is part of a correct answer (e.g. the query itself
   * requires ORDER BY/LIMIT). Otherwise results are compared as sets. */
  orderMatters?: boolean
  hint: string
}

// 24 questions spanning every topic in the SQL Practice curriculum. Each
// solutionQuery is executed live against a fresh copy of the sample database
// to produce the expected result — see lib/sqlEngine.ts and lib/grading.ts —
// rather than hand-written result sets, so there's one source of truth.
export const sqlQuestions: SqlQuestion[] = [
  {
    id: 'basics-select-all',
    title: 'All employees',
    difficulty: 'Easy',
    topic: 'Basics',
    prompt: 'Return every column for every row in the employees table.',
    solutionQuery: 'SELECT * FROM employees;',
    hint: 'SELECT * FROM <table>;',
  },
  {
    id: 'filter-expensive-products',
    title: 'Expensive products',
    difficulty: 'Easy',
    topic: 'Filtering',
    prompt: 'Return product_name and price for products priced above $50.',
    solutionQuery: 'SELECT product_name, price FROM products WHERE price > 50;',
    hint: 'Use a WHERE clause with a > comparison.',
  },
  {
    id: 'filter-usa-customers',
    title: 'Customers from the USA',
    difficulty: 'Easy',
    topic: 'Filtering',
    prompt:
      "Return first_name, last_name, email for customers whose country is 'USA'.",
    solutionQuery:
      "SELECT first_name, last_name, email FROM customers WHERE country = 'USA';",
    hint: "WHERE country = 'USA'",
  },
  {
    id: 'sort-top-salaries',
    title: 'Top 3 salaries',
    difficulty: 'Easy',
    topic: 'Sorting & Limiting',
    prompt:
      'Return first_name, last_name, salary for the 3 highest-paid employees, ordered from highest to lowest salary.',
    solutionQuery:
      'SELECT first_name, last_name, salary FROM employees ORDER BY salary DESC LIMIT 3;',
    orderMatters: true,
    hint: 'ORDER BY salary DESC combined with LIMIT.',
  },
  {
    id: 'count-completed-orders',
    title: 'Completed order count',
    difficulty: 'Easy',
    topic: 'Aggregation',
    prompt:
      "Return the total number of orders with status = 'completed'. Name the column completed_orders.",
    solutionQuery:
      "SELECT COUNT(*) AS completed_orders FROM orders WHERE status = 'completed';",
    hint: 'COUNT(*) combined with a WHERE filter.',
  },
  {
    id: 'string-full-name',
    title: 'Full employee names',
    difficulty: 'Easy',
    topic: 'String Functions',
    prompt:
      'Return employee_id and a full_name column that joins first_name and last_name with a space in between.',
    solutionQuery:
      "SELECT employee_id, first_name || ' ' || last_name AS full_name FROM employees;",
    hint: "SQLite concatenates strings with the || operator.",
  },
  {
    id: 'join-employee-department',
    title: 'Employees with department names',
    difficulty: 'Medium',
    topic: 'Joins',
    prompt: "Return each employee's first_name, last_name, and their department_name.",
    solutionQuery:
      'SELECT e.first_name, e.last_name, d.department_name FROM employees e JOIN departments d ON e.department_id = d.department_id;',
    hint: 'INNER JOIN employees to departments on department_id.',
  },
  {
    id: 'aggregate-product-revenue',
    title: 'Revenue per product',
    difficulty: 'Medium',
    topic: 'Aggregation',
    prompt:
      'Return product_name and total revenue (quantity * unit_price, summed) generated by each product, aliased as total_revenue.',
    solutionQuery:
      'SELECT p.product_name, SUM(s.quantity * s.unit_price) AS total_revenue FROM sales s JOIN products p ON s.product_id = p.product_id GROUP BY p.product_name;',
    hint: 'JOIN sales to products, then GROUP BY product_name.',
  },
  {
    id: 'date-signups-2022',
    title: 'Customers who signed up in 2022',
    difficulty: 'Medium',
    topic: 'Date Functions',
    prompt:
      'Return first_name, last_name for customers who signed up in the year 2022, using a date function on signup_date.',
    solutionQuery:
      "SELECT first_name, last_name FROM customers WHERE strftime('%Y', signup_date) = '2022';",
    hint: "strftime('%Y', signup_date) extracts the year from a date string.",
  },
  {
    id: 'case-seniority',
    title: 'Seniority label',
    difficulty: 'Medium',
    topic: 'CASE WHEN',
    prompt:
      "Return first_name, last_name, salary and a seniority column: 'Senior' if salary > 120000, otherwise 'Junior'.",
    solutionQuery:
      "SELECT first_name, last_name, salary, CASE WHEN salary > 120000 THEN 'Senior' ELSE 'Junior' END AS seniority FROM employees;",
    hint: 'CASE WHEN <condition> THEN <value> ELSE <value> END',
  },
  {
    id: 'join-manager-self',
    title: 'Employees and their managers',
    difficulty: 'Medium',
    topic: 'Joins',
    prompt:
      "Return each employee's first_name/last_name alongside their manager's first_name/last_name (aliased manager_first_name, manager_last_name). Only include employees who have a manager.",
    solutionQuery:
      'SELECT e.first_name, e.last_name, m.first_name AS manager_first_name, m.last_name AS manager_last_name FROM employees e JOIN employees m ON e.manager_id = m.employee_id;',
    hint: 'Join the employees table to itself using manager_id = employee_id.',
  },
  {
    id: 'having-multi-item-orders',
    title: 'Orders with multiple line items',
    difficulty: 'Medium',
    topic: 'Aggregation',
    prompt:
      'Return order_id and the number of line items (rows in sales) for orders that have more than 1 line item, aliased as item_count.',
    solutionQuery:
      'SELECT order_id, COUNT(*) AS item_count FROM sales GROUP BY order_id HAVING COUNT(*) > 1;',
    hint: 'HAVING filters on an aggregate, unlike WHERE.',
  },
  {
    id: 'string-case-transform',
    title: 'Upper/lower case transforms',
    difficulty: 'Medium',
    topic: 'String Functions',
    prompt:
      'Return product_name in uppercase (as product_name_upper) and category in lowercase (as category_lower) for every product.',
    solutionQuery:
      'SELECT UPPER(product_name) AS product_name_upper, LOWER(category) AS category_lower FROM products;',
    hint: 'UPPER() and LOWER() transform text case.',
  },
  {
    id: 'window-salary-rank',
    title: 'Salary rank within department',
    difficulty: 'Hard',
    topic: 'Window Functions',
    prompt:
      'For every employee, return first_name, last_name, department_id, salary, and their salary rank within their department (1 = highest paid), aliased as salary_rank. Order the result by department_id, then salary_rank.',
    solutionQuery:
      'SELECT first_name, last_name, department_id, salary, RANK() OVER (PARTITION BY department_id ORDER BY salary DESC) AS salary_rank FROM employees ORDER BY department_id, salary_rank;',
    orderMatters: true,
    hint: 'RANK() OVER (PARTITION BY ... ORDER BY ...)',
  },
  {
    id: 'window-running-total',
    title: 'Running total of sales',
    difficulty: 'Hard',
    topic: 'Window Functions',
    prompt:
      'Return sale_id and a running total of (quantity * unit_price) ordered by sale_id, aliased as running_total.',
    solutionQuery:
      'SELECT sale_id, SUM(quantity * unit_price) OVER (ORDER BY sale_id) AS running_total FROM sales ORDER BY sale_id;',
    orderMatters: true,
    hint: 'A window SUM() with ORDER BY (and no PARTITION BY) accumulates a running total.',
  },
  {
    id: 'window-second-highest-salary',
    title: 'Second-highest salary per department',
    difficulty: 'Hard',
    topic: 'Window Functions',
    prompt:
      'Return department_id and the second-highest salary in that department, aliased as second_highest_salary. Skip departments with fewer than 2 employees.',
    solutionQuery:
      'WITH ranked AS (SELECT department_id, salary, RANK() OVER (PARTITION BY department_id ORDER BY salary DESC) AS rnk FROM employees) SELECT department_id, salary AS second_highest_salary FROM ranked WHERE rnk = 2;',
    hint: 'Rank salaries per department in a CTE, then filter WHERE rnk = 2.',
  },
  {
    id: 'join-customers-no-orders',
    title: 'Customers with no orders',
    difficulty: 'Hard',
    topic: 'Joins',
    prompt: 'Return first_name, last_name for customers who have never placed an order.',
    solutionQuery:
      'SELECT c.first_name, c.last_name FROM customers c LEFT JOIN orders o ON c.customer_id = o.customer_id WHERE o.order_id IS NULL;',
    hint: 'A LEFT JOIN followed by WHERE <right side> IS NULL finds unmatched rows.',
  },
  {
    id: 'date-tenure-years',
    title: 'Employee tenure in years',
    difficulty: 'Hard',
    topic: 'Date Functions',
    prompt:
      "Return first_name, last_name, and tenure_years — each employee's tenure in whole years between hire_date and 2023-12-31.",
    solutionQuery:
      "SELECT first_name, last_name, CAST((julianday('2023-12-31') - julianday(hire_date)) / 365 AS INTEGER) AS tenure_years FROM employees;",
    hint: "julianday() converts a date to a day count so you can subtract two dates.",
  },
  {
    id: 'view-top-order-totals',
    title: 'View: top order totals',
    difficulty: 'Hard',
    topic: 'Views',
    prompt:
      'Create a view named order_totals with order_id and total (SUM of quantity*unit_price from sales) per order. Then select order_id and total from that view for the top 3 orders by total, ordered highest first.',
    solutionQuery:
      'CREATE VIEW order_totals AS SELECT order_id, SUM(quantity * unit_price) AS total FROM sales GROUP BY order_id; SELECT order_id, total FROM order_totals ORDER BY total DESC LIMIT 3;',
    orderMatters: true,
    hint: 'CREATE VIEW <name> AS <select>; then query the view like a table in a second statement.',
  },
  {
    id: 'antijoin-unsold-products',
    title: 'Products never sold',
    difficulty: 'Interview',
    topic: 'Subqueries',
    prompt:
      'Return product_name for products that have never appeared in the sales table. Prefer a LEFT JOIN or NOT EXISTS over a NOT IN subquery — NOT IN silently returns zero rows if the subquery contains a NULL, a common interview gotcha.',
    solutionQuery:
      'SELECT p.product_name FROM products p LEFT JOIN sales s ON p.product_id = s.product_id WHERE s.sale_id IS NULL;',
    hint: 'Same anti-join pattern as "customers with no orders", applied to products/sales.',
  },
  {
    id: 'index-completed-orders-per-employee',
    title: 'Completed orders per employee',
    difficulty: 'Interview',
    topic: 'Indexes & Query Optimization',
    prompt:
      "An index on orders.employee_id already exists in this schema (see datasets/seed.sql) to speed up exactly this kind of lookup. Return employee_id and the number of completed orders they've handled, aliased as completed_count, for employees with at least 1 completed order.",
    solutionQuery:
      "SELECT employee_id, COUNT(*) AS completed_count FROM orders WHERE status = 'completed' GROUP BY employee_id HAVING COUNT(*) >= 1;",
    hint: 'Filter by status, GROUP BY employee_id, then COUNT(*). Try EXPLAIN QUERY PLAN <your query> to see the index in use.',
  },
  {
    id: 'window-latest-order-per-customer',
    title: 'Latest order per customer',
    difficulty: 'Interview',
    topic: 'Window Functions',
    prompt:
      "Return each customer's customer_id and their single most recent order_id and order_date.",
    solutionQuery:
      'WITH ranked_orders AS (SELECT customer_id, order_id, order_date, ROW_NUMBER() OVER (PARTITION BY customer_id ORDER BY order_date DESC) AS rn FROM orders) SELECT customer_id, order_id, order_date FROM ranked_orders WHERE rn = 1;',
    hint: 'The classic "top 1 per group" pattern: ROW_NUMBER() in a CTE, then filter WHERE rn = 1.',
  },
  {
    id: 'top-customers-by-spend',
    title: 'Top 3 customers by spend',
    difficulty: 'Interview',
    topic: 'Joins',
    prompt:
      "Return customer_id and total amount spent (SUM of quantity*unit_price across their orders' sales), aliased as total_spent, for the top 3 customers, ordered highest first.",
    solutionQuery:
      'SELECT o.customer_id, SUM(s.quantity * s.unit_price) AS total_spent FROM orders o JOIN sales s ON o.order_id = s.order_id GROUP BY o.customer_id ORDER BY total_spent DESC LIMIT 3;',
    orderMatters: true,
    hint: 'Join orders to sales, GROUP BY customer, then ORDER BY the aggregate DESC with LIMIT.',
  },
  {
    id: 'subquery-above-department-average',
    title: 'Above department average',
    difficulty: 'Interview',
    topic: 'Subqueries',
    prompt:
      'Return first_name, last_name, department_id, salary for employees who earn more than the average salary of their own department.',
    solutionQuery:
      'SELECT e.first_name, e.last_name, e.department_id, e.salary FROM employees e WHERE e.salary > (SELECT AVG(e2.salary) FROM employees e2 WHERE e2.department_id = e.department_id);',
    hint: 'A correlated subquery recomputes AVG(salary) per outer row, scoped to the same department_id.',
  },
]
